version: '3'

services:
  redis:
    image: redis
    command: redis-server --requirepass 12345678
    ports:
      - "6379:6379"
  
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - "5000:80"
      - "5001:443"
    links:
      - "redis:redis"